In [8]:
import pandas as pd

In [32]:
#Visualizar e explorar a tabela de Usuários (consumers.csv)
consumer = pd.read_csv("../data/consumer.csv.gz")
display(consumer.head())
display(consumer.info())

#Tratamento da tabela de Usuários (consumers.csv)
consumer = consumer.drop_duplicates(subset='customer_id')
consumer.drop(columns=['language', 'customer_name', 'customer_phone_number'], inplace=True)
consumer['created_at'] = pd.to_datetime(consumer['created_at'])
consumer['ano_mes'] = consumer['created_at'].dt.to_period('M')
consumer['customer_phone_area'] = consumer['customer_phone_area'].astype(str)
consumer_order = ['customer_id', 'created_at', 'ano_mes', 'active', 'customer_phone_area']
consumer = consumer[consumer_order]
display(consumer.head())
display(consumer.info())

,customer_id,language,created_at,active,customer_name,customer_phone_area,customer_phone_number
0,e8cc60860e09c0bb19610b06ced69c973eb83982cfc98e...,pt-br,2018-04-05T14:49:18.165Z,True,NUNO,46,816135924
1,a2834a38a9876cf74e016524dd2e8c1f010ee12b2b684d...,pt-br,2018-01-14T21:40:02.141Z,True,ADRIELLY,59,231330577
2,41e1051728eba13341136d67d0757f8d8cc44b2a405b71...,pt-br,2018-01-07T03:47:15.554Z,True,PAULA,62,347597883
3,8e7c1dcb64edf95c935147f6d560cb068c44714cb1b21b...,pt-br,2018-01-10T22:17:08.160Z,True,HELTON,13,719366842
4,7823d4cf4150c5daeae0bd799206852fc123bdef0cf5d1...,pt-br,2018-04-06T00:16:20.935Z,True,WENDER,76,543232158

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806156 entries, 0 to 806155
Data columns (total 7 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            806156 non-null  object
 1   language               806156 non-null  object
 2   created_at             806156 non-null  object
 3   active                 806156 non-null  bool
 4   customer_name          806155 non-null  object
 5   customer_phone_area    806156 non-null  int64
 6   customer_phone_number  806156 non-null  int64
dtypes: bool(1), int64(2), object(4)
memory usage: 37.7+ MB

None

/tmp/ipykernel_571149/2920086053.py:10: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  consumer['ano_mes'] = consumer['created_at'].dt.to_period('M')

,customer_id,created_at,ano_mes,active,customer_phone_area
0,e8cc60860e09c0bb19610b06ced69c973eb83982cfc98e...,2018-04-05 14:49:18.165000+00:00,2018-04,True,46
1,a2834a38a9876cf74e016524dd2e8c1f010ee12b2b684d...,2018-01-14 21:40:02.141000+00:00,2018-01,True,59
2,41e1051728eba13341136d67d0757f8d8cc44b2a405b71...,2018-01-07 03:47:15.554000+00:00,2018-01,True,62
3,8e7c1dcb64edf95c935147f6d560cb068c44714cb1b21b...,2018-01-10 22:17:08.160000+00:00,2018-01,True,13
4,7823d4cf4150c5daeae0bd799206852fc123bdef0cf5d1...,2018-04-06 00:16:20.935000+00:00,2018-04,True,76

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806156 entries, 0 to 806155
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          806156 non-null  object
 1   created_at           806156 non-null  datetime64[ns, UTC]
 2   ano_mes              806156 non-null  period[M]
 3   active               806156 non-null  bool
 4   customer_phone_area  806156 non-null  object
dtypes: bool(1), datetime64[ns, UTC](1), object(2), period[M](1)
memory usage: 25.4+ MB

None

In [35]:
#Extrair o arquivo ab_test_ref.tar.gz
import tarfile

with tarfile.open("../data/ab_test_ref.tar.gz", "r:gz") as tar:
    tar.extractall(path="../data/ab_test_ref")

#Visualizar e explorar a tabela de Marcação de usuários que participaram do teste A/B (ab_test_ref.csv)
ab_test = pd.read_csv("../data/ab_test_ref/ab_test_ref.csv")
display(ab_test.head())
display(ab_test.info())

#Tratamento da tabela de Marcação de usuários que participaram do teste A/B (ab_test_ref.csv)
ab_test = ab_test.dropna(subset=['customer_id'])
ab_test = ab_test.drop_duplicates(subset='customer_id')
display(ab_test.head())
display(ab_test.info())

/tmp/ipykernel_571149/1453668088.py:5: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path="../data/ab_test_ref")

                                         customer_id is_target
0  755e1fa18f25caec5edffb188b13fd844b2af8cf5adedc...    target
1  b821aa8372b8e5b82cdc283742757df8c45eecdd72adf4...   control
2  d425d6ee4c9d4e211b71da8fc60bf6c5336b2ea9af9cc0...   control
3  6a7089eea0a5dc294fbccd4fa24d0d84a90c1cc12e829c...    target
4  dad6b7e222bab31c0332b0ccd9fa5dbd147008facd268f...   control

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806467 entries, 0 to 806466
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  806466 non-null  object
 1   is_target    806467 non-null  object
dtypes: object(2)
memory usage: 12.3+ MB

None

                                         customer_id is_target
0  755e1fa18f25caec5edffb188b13fd844b2af8cf5adedc...    target
1  b821aa8372b8e5b82cdc283742757df8c45eecdd72adf4...   control
2  d425d6ee4c9d4e211b71da8fc60bf6c5336b2ea9af9cc0...   control
3  6a7089eea0a5dc294fbccd4fa24d0d84a90c1cc12e829c...    target
4  dad6b7e222bab31c0332b0ccd9fa5dbd147008facd268f...   control

<class 'pandas.core.frame.DataFrame'>
Index: 806466 entries, 0 to 806466
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  806466 non-null  object
 1   is_target    806466 non-null  object
dtypes: object(2)
memory usage: 18.5+ MB

None

In [44]:
#Visualizar e explorar a tabela de Merchants (restaurant.csv)
restaurant = pd.read_csv("../data/restaurant.csv.gz")
display(restaurant.head())
display(restaurant.info())

#Tratamento da tabela de de Merchants (restaurant.csv)
restaurant = restaurant.drop_duplicates(subset='id')
restaurant.drop(columns=['takeout_time', 'merchant_zip_code', 'merchant_city', 'merchant_country'], inplace=True)
restaurant['created_at'] = pd.to_datetime(consumer['created_at'])
restaurant['ano_mes'] = consumer['created_at'].dt.to_period('M')
col = 'ano_mes'
cols = list(restaurant.columns)
cols.remove(col)
cols.insert(2, col)
restaurant = restaurant[cols]
display(restaurant.head())
display(restaurant.info())

,id,created_at,enabled,price_range,average_ticket,takeout_time,delivery_time,minimum_order_value,merchant_zip_code,merchant_city,merchant_state,merchant_country
0,d19ff6fca6288939bff073ad0a119d25c0365c407e9e5d...,2017-01-23T12:52:30.910Z,False,3,60.0,0,50.0,30.0,14025,RIBEIRAO PRETO,SP,BR
1,631df0985fdbbaf27b9b031a8f381924e3483833385748...,2017-01-20T13:14:48.286Z,True,3,60.0,0,0.0,30.0,50180,SAO PAULO,SP,BR
2,135c5c4ae4c1ec1fdc23e8c649f313e39be8db913d8bc5...,2017-01-23T12:46:33.457Z,True,5,100.0,0,45.0,10.0,23090,RIO DE JANEIRO,RJ,BR
3,d26f84c470451f752bef036c55517b6d9950d41806f10e...,2017-01-20T13:15:04.806Z,True,3,80.0,0,0.0,18.9,40255,SALVADOR,BA,BR
4,97b9884600ea7192314580d9115f8882b8634f5aa201ff...,2017-01-20T13:14:27.701Z,True,3,60.0,0,0.0,25.0,64600,BARUERI,SP,BR

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7292 entries, 0 to 7291
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7292 non-null   object
 1   created_at           7292 non-null   object
 2   enabled              7292 non-null   bool
 3   price_range          7292 non-null   int64
 4   average_ticket       7292 non-null   float64
 5   takeout_time         7292 non-null   int64
 6   delivery_time        7291 non-null   float64
 7   minimum_order_value  7197 non-null   float64
 8   merchant_zip_code    7292 non-null   int64
 9   merchant_city        7292 non-null   object
 10  merchant_state       7292 non-null   object
 11  merchant_country     7292 non-null   object
dtypes: bool(1), float64(3), int64(3), object(5)
memory usage: 633.9+ KB

None

/tmp/ipykernel_571149/3684962530.py:10: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  restaurant['ano_mes'] = consumer['created_at'].dt.to_period('M')

,id,created_at,ano_mes,enabled,price_range,average_ticket,delivery_time,minimum_order_value,merchant_state
0,d19ff6fca6288939bff073ad0a119d25c0365c407e9e5d...,2018-04-05 14:49:18.165000+00:00,2018-04,False,3,60.0,50.0,30.0,SP
1,631df0985fdbbaf27b9b031a8f381924e3483833385748...,2018-01-14 21:40:02.141000+00:00,2018-01,True,3,60.0,0.0,30.0,SP
2,135c5c4ae4c1ec1fdc23e8c649f313e39be8db913d8bc5...,2018-01-07 03:47:15.554000+00:00,2018-01,True,5,100.0,45.0,10.0,RJ
3,d26f84c470451f752bef036c55517b6d9950d41806f10e...,2018-01-10 22:17:08.160000+00:00,2018-01,True,3,80.0,0.0,18.9,BA
4,97b9884600ea7192314580d9115f8882b8634f5aa201ff...,2018-04-06 00:16:20.935000+00:00,2018-04,True,3,60.0,0.0,25.0,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7292 entries, 0 to 7291
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7292 non-null   object
 1   created_at           7292 non-null   datetime64[ns, UTC]
 2   ano_mes              7292 non-null   period[M]
 3   enabled              7292 non-null   bool
 4   price_range          7292 non-null   int64
 5   average_ticket       7292 non-null   float64
 6   delivery_time        7291 non-null   float64
 7   minimum_order_value  7197 non-null   float64
 8   merchant_state       7292 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), float64(3), int64(1), object(2), period[M](1)
memory usage: 463.0+ KB

None

In [53]:
#Visualizar e explorar a tabela de Pedidos (order.json)
chunks_order = pd.read_json("../data/order.json.gz", lines=True, compression='gzip', chunksize=100_000)
first_chunk = next(chunks_order)
display(first_chunk.head())
display(first_chunk.info())

#Tratamento da tabela de Pedidos (order.json)
chunks_order = pd.read_json("../data/order.json.gz", lines=True, compression='gzip', chunksize=100_000)

order_columns=['customer_id', 'delivery_address_state', 'merchant_id', 'order_created_at', 'order_id', 'order_scheduled', 'order_total_amount', 'origin_platform', 'order_scheduled_date']

order_clean = []

for order_cleaning in chunks_order:
    order_cleaning = order_cleaning.dropna(subset=['customer_id'])
    order_cleaning = order_cleaning[order_columns]
    order_cleaning['order_scheduled_date'] = pd.to_datetime(order_cleaning['order_scheduled_date'])
    order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
    order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
    col = 'ano_mes_created_at'
    cols = list(order_cleaning.columns)
    cols.remove(col)
    cols.insert(4, col)
    order_cleaning = order_cleaning[cols]

    order_clean.append(order_cleaning)

order_clean = pd.concat(order_clean, ignore_index=True)

display(order_clean.head())
display(order_clean.info())

,cpf,customer_id,customer_name,delivery_address_city,delivery_address_country,delivery_address_district,delivery_address_external_id,delivery_address_latitude,delivery_address_longitude,delivery_address_state,...,merchant_id,merchant_latitude,merchant_longitude,merchant_timezone,order_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date
0,80532101763,7ba88a68bb2a3504c6bd37a707af57a0b8d6e110a551c7...,GUSTAVO,FRANCA,BR,JARDIM ESPRAIADO,6736655,-47.39,-20.55,SP,...,a992a079a651e699d9149423761df2427c0e3af0a2a1b5...,-47.39,-20.55,America/Sao_Paulo,2019-01-17 22:50:06+00:00,33e0612d62e5eb42aba15b58413137e441fbe906de2feb...,False,46.0,ANDROID,NaN
1,43352103961,078acecdcf7fa89d356bfa349f14a8219db1ee161ce28a...,MICHELLE,SANTOS,BR,CAMPO GRANDE,8759216,-46.34,-23.96,SP,...,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,-46.34,-23.96,America/Sao_Paulo,2019-01-17 17:51:26+00:00,148c4353a2952f3fe7973547283265eb22b575fb712ed2...,False,104.5,ANDROID,NaN
2,38650991217,0e38a3237b5946e8ab2367b4f1a3ae6e77f1e215bc760c...,VICTOR,GUARULHOS,BR,JARDIM ROSSI,8765930,-46.53,-23.44,SP,...,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,-46.53,-23.44,America/Sao_Paulo,2019-01-17 22:53:47+00:00,c37e495a91b498bb7b70a9e09ac115d0cdd443f152dc11...,False,35.0,IOS,NaN
3,63579726866,cab1a004b7206d07910092c515a79834fea0a03d7d9054...,ANNIE,SAO PAULO,BR,PARQUE SAO JORGE,7834087,-46.57,-23.53,SP,...,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,-46.57,-23.53,America/Sao_Paulo,2019-01-17 23:56:53+00:00,b4df94142d21354611247da9ca94f870c09b93989b531a...,False,40.8,IOS,NaN
4,90617788806,aa7edf5b166b8c843aec3b96dc561222888734f3879123...,DANIEL,VITORIA,BR,JARDIM CAMBURI,7211683,-40.27,-20.25,ES,...,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,-40.27,-20.25,America/Sao_Paulo,2019-01-17 23:40:53+00:00,4ff64b33b272c1886df21b63272220af6a82d1667dba70...,False,48.5,ANDROID,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   cpf                           100000 non-null  int64
 1   customer_id                   99784 non-null   object
 2   customer_name                 100000 non-null  object
 3   delivery_address_city         100000 non-null  object
 4   delivery_address_country      100000 non-null  object
 5   delivery_address_district     100000 non-null  object
 6   delivery_address_external_id  100000 non-null  int64
 7   delivery_address_latitude     100000 non-null  float64
 8   delivery_address_longitude    100000 non-null  float64
 9   delivery_address_state        100000 non-null  object
 10  delivery_address_zip_code     100000 non-null  int64
 11  items                         100000 non-null  object
 12  merchant_id                   100000 non-null  object
 13  merchant_latitude             100000 non-null  float64
 14  merchant_longitude            100000 non-null  float64
 15  merchant_timezone             100000 non-null  object
 16  order_created_at              100000 non-null  datetime64[ns, UTC]
 17  order_id                      100000 non-null  object
 18  order_scheduled               100000 non-null  bool
 19  order_total_amount            100000 non-null  float64
 20  origin_platform               100000 non-null  object
 21  order_scheduled_date          16 non-null      object
dtypes: bool(1), datetime64[ns, UTC](1), float64(5), int64(3), object(12)
memory usage: 16.1+ MB

None

/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:18: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_created_at'] = order_cleaning['order_created_at'].dt.to_period('M')
/tmp/ipykernel_571149/4130182647.py:19: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  order_cleaning['ano_mes_scheduled_date'] = order_cleaning['order_scheduled_date'].dt.to_period('M')

,customer_id,delivery_address_state,merchant_id,order_created_at,ano_mes_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date,ano_mes_scheduled_date
0,7ba88a68bb2a3504c6bd37a707af57a0b8d6e110a551c7...,SP,a992a079a651e699d9149423761df2427c0e3af0a2a1b5...,2019-01-17 22:50:06+00:00,2019-01,33e0612d62e5eb42aba15b58413137e441fbe906de2feb...,False,46.0,ANDROID,NaT,NaT
1,078acecdcf7fa89d356bfa349f14a8219db1ee161ce28a...,SP,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,2019-01-17 17:51:26+00:00,2019-01,148c4353a2952f3fe7973547283265eb22b575fb712ed2...,False,104.5,ANDROID,NaT,NaT
2,0e38a3237b5946e8ab2367b4f1a3ae6e77f1e215bc760c...,SP,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,2019-01-17 22:53:47+00:00,2019-01,c37e495a91b498bb7b70a9e09ac115d0cdd443f152dc11...,False,35.0,IOS,NaT,NaT
3,cab1a004b7206d07910092c515a79834fea0a03d7d9054...,SP,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,2019-01-17 23:56:53+00:00,2019-01,b4df94142d21354611247da9ca94f870c09b93989b531a...,False,40.8,IOS,NaT,NaT
4,aa7edf5b166b8c843aec3b96dc561222888734f3879123...,ES,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,2019-01-17 23:40:53+00:00,2019-01,4ff64b33b272c1886df21b63272220af6a82d1667dba70...,False,48.5,ANDROID,NaT,NaT

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3662321 entries, 0 to 3662320
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   customer_id             object
 1   delivery_address_state  object
 2   merchant_id             object
 3   order_created_at        datetime64[ns, UTC]
 4   ano_mes_created_at      period[M]
 5   order_id                object
 6   order_scheduled         bool
 7   order_total_amount      float64
 8   origin_platform         object
 9   order_scheduled_date    datetime64[ns, UTC]
 10  ano_mes_scheduled_date  period[M]
dtypes: bool(1), datetime64[ns, UTC](2), float64(1), object(5), period[M](2)
memory usage: 282.9+ MB

None

In [55]:
#Salvando os dados tratados da tabela de Pedidos (order.json)
order_clean.to_parquet("order_clean.parquet", index=False)

In [57]:
#Visualizar a tabela de Pedidos tratada (order_clean.parquet)
order = pd.read_parquet("../data/order_clean.parquet")
display(order.head())
display(order.info())

,customer_id,delivery_address_state,merchant_id,order_created_at,ano_mes_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date,ano_mes_scheduled_date
0,7ba88a68bb2a3504c6bd37a707af57a0b8d6e110a551c7...,SP,a992a079a651e699d9149423761df2427c0e3af0a2a1b5...,2019-01-17 22:50:06+00:00,2019-01,33e0612d62e5eb42aba15b58413137e441fbe906de2feb...,False,46.0,ANDROID,NaT,NaT
1,078acecdcf7fa89d356bfa349f14a8219db1ee161ce28a...,SP,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,2019-01-17 17:51:26+00:00,2019-01,148c4353a2952f3fe7973547283265eb22b575fb712ed2...,False,104.5,ANDROID,NaT,NaT
2,0e38a3237b5946e8ab2367b4f1a3ae6e77f1e215bc760c...,SP,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,2019-01-17 22:53:47+00:00,2019-01,c37e495a91b498bb7b70a9e09ac115d0cdd443f152dc11...,False,35.0,IOS,NaT,NaT
3,cab1a004b7206d07910092c515a79834fea0a03d7d9054...,SP,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,2019-01-17 23:56:53+00:00,2019-01,b4df94142d21354611247da9ca94f870c09b93989b531a...,False,40.8,IOS,NaT,NaT
4,aa7edf5b166b8c843aec3b96dc561222888734f3879123...,ES,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,2019-01-17 23:40:53+00:00,2019-01,4ff64b33b272c1886df21b63272220af6a82d1667dba70...,False,48.5,ANDROID,NaT,NaT

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3662321 entries, 0 to 3662320
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   customer_id             object
 1   delivery_address_state  object
 2   merchant_id             object
 3   order_created_at        datetime64[ns, UTC]
 4   ano_mes_created_at      period[M]
 5   order_id                object
 6   order_scheduled         bool
 7   order_total_amount      float64
 8   origin_platform         object
 9   order_scheduled_date    datetime64[ns, UTC]
 10  ano_mes_scheduled_date  period[M]
dtypes: bool(1), datetime64[ns, UTC](2), float64(1), object(5), period[M](2)
memory usage: 282.9+ MB

None