In [1]:
import pandas as pd

In [2]:
#Visualizar e explorar a tabela de Usuários (consumers.csv)
consumer = pd.read_csv("../data/consumer.csv.gz")
display(consumer.head())

FileNotFoundError: [Errno 2] No such file or directory: '../data/consumer.csv.gz'

In [ ]:
#Extrair o arquivo ab_test_ref.tar.gz
import tarfile

with tarfile.open("../data/ab_test_ref.tar.gz", "r:gz") as tar:
    tar.extractall(path="../data/ab_test_ref")

#Visualizar e explorar a tabela de Marcação de usuários que participaram do teste A/B (ab_test_ref.csv)
ab_test = pd.read_csv("../data/ab_test_ref/ab_test_ref.csv")
display(ab_test.head())

/tmp/ipykernel_502236/1695985728.py:5: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path="../data/ab_test_ref")

                                         customer_id is_target
0  755e1fa18f25caec5edffb188b13fd844b2af8cf5adedc...    target
1  b821aa8372b8e5b82cdc283742757df8c45eecdd72adf4...   control
2  d425d6ee4c9d4e211b71da8fc60bf6c5336b2ea9af9cc0...   control
3  6a7089eea0a5dc294fbccd4fa24d0d84a90c1cc12e829c...    target
4  dad6b7e222bab31c0332b0ccd9fa5dbd147008facd268f...   control

In [ ]:
#Visualizar e explorar a tabela de Merchants (restaurant.csv)
restaurant = pd.read_csv("../data/restaurant.csv.gz")
display(restaurant.head())

,id,created_at,enabled,price_range,average_ticket,takeout_time,delivery_time,minimum_order_value,merchant_zip_code,merchant_city,merchant_state,merchant_country
0,d19ff6fca6288939bff073ad0a119d25c0365c407e9e5d...,2017-01-23T12:52:30.910Z,False,3,60.0,0,50.0,30.0,14025,RIBEIRAO PRETO,SP,BR
1,631df0985fdbbaf27b9b031a8f381924e3483833385748...,2017-01-20T13:14:48.286Z,True,3,60.0,0,0.0,30.0,50180,SAO PAULO,SP,BR
2,135c5c4ae4c1ec1fdc23e8c649f313e39be8db913d8bc5...,2017-01-23T12:46:33.457Z,True,5,100.0,0,45.0,10.0,23090,RIO DE JANEIRO,RJ,BR
3,d26f84c470451f752bef036c55517b6d9950d41806f10e...,2017-01-20T13:15:04.806Z,True,3,80.0,0,0.0,18.9,40255,SALVADOR,BA,BR
4,97b9884600ea7192314580d9115f8882b8634f5aa201ff...,2017-01-20T13:14:27.701Z,True,3,60.0,0,0.0,25.0,64600,BARUERI,SP,BR

In [ ]:
#Visualizar e explorar a tabela de Pedidos (order.json)
order = pd.read_json("../data/order.json.gz", lines=True, compression='gzip', chunksize=100_000)
order = next(order)
display(order.head(1))

,cpf,customer_id,customer_name,delivery_address_city,delivery_address_country,delivery_address_district,delivery_address_external_id,delivery_address_latitude,delivery_address_longitude,delivery_address_state,...,merchant_id,merchant_latitude,merchant_longitude,merchant_timezone,order_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date
0,80532101763,7ba88a68bb2a3504c6bd37a707af57a0b8d6e110a551c7...,GUSTAVO,FRANCA,BR,JARDIM ESPRAIADO,6736655,-47.39,-20.55,SP,...,a992a079a651e699d9149423761df2427c0e3af0a2a1b5...,-47.39,-20.55,America/Sao_Paulo,2019-01-17 22:50:06+00:00,33e0612d62e5eb42aba15b58413137e441fbe906de2feb...,False,46.0,ANDROID,NaN